spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  redis:
    host: 18.139.222.137
    port: 6379
    password: 'hhhhhhhhhhsdvnsldvmsdlvmsdlkvmsdv'
    database: 1
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
      shutdown-timeout: 200ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: acc-svc
          uri: 'lb://acc-svc'
          predicates:
            - Path=/acc-svc/**
          filters:
            - 'RewritePath=/acc-svc/(?<path>.*), /$\{path}'
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        - id: api-svc
          uri: 'lb://api-svc'
          predicates:
            - Path=/api-svc/**
          filters:
            - 'RewritePath=/api-svc/(?<path>.*), /$\{path}'
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        - id: upload-svc
          uri: 'lb://upload-svc'
          predicates:
            - Path=/upload-svc/**
          filters:
            - 'RewritePath=/upload-svc/(?<path>.*), /$\{path}'
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
server:
  port: '${GATEWAY_PORT:30001}'
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
eureka:
  client:
    serviceUrl:
      defaultZone: '${EUREKA_URI:http://localhost:30300/eureka/}'
hystrix:
  command:
    enrollmentsvc:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
enrollmentsvc:
  ribbon:
    ConnectTimeout: 20000
    ReadTimeout: 20000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
logging:
  config: config/log4j2.xml



